<?php

declare(strict_types=1);

namespace Brigmaster\Application;

use Brigmaster\Domain\DTO\EstimateInput;
use Brigmaster\Domain\DTO\EstimateResult;
use InvalidArgumentException;

final class EstimateService
{
    public const CALCULATOR_BRICK = 'brick';
    public const CALCULATOR_SCREED = 'screed';
    public const CALCULATOR_DRYWALL = 'drywall';
    public const CALCULATOR_TILE = 'tile';
    public const CALCULATOR_SLAB_FOUNDATION = 'slab_foundation';
    public const CALCULATOR_STRIP_FOUNDATION = 'strip_foundation';
    public const CALCULATOR_PILE_FOUNDATION = 'pile_foundation';

    /** @var array<int, string> Canonical list of supported calculator slugs (single source of truth). */
    public const ALLOWED_CALCULATORS = [
        self::CALCULATOR_BRICK,
        self::CALCULATOR_SCREED,
        self::CALCULATOR_DRYWALL,
        self::CALCULATOR_TILE,
        self::CALCULATOR_SLAB_FOUNDATION,
        self::CALCULATOR_STRIP_FOUNDATION,
        self::CALCULATOR_PILE_FOUNDATION,
    ];

    public function __construct(
        private readonly CalculatorRegistry $calculatorRegistry = new CalculatorRegistry()
    ) {
    }

    public function calculate(
        string $calculator,
        string $mode,
        ?float $area = null,
        ?float $thickness = null,
        ?string $subType = null,
        ?float $tileLengthCm = null,
        ?float $tileWidthCm = null,
        ?float $length = null,
        ?float $width = null,
        ?float $height = null,
        ?bool $includeReinforcement = null,
        ?bool $includeFormwork = null,
        ?float $rebarDiameterMm = null,
        ?float $rebarStepMm = null,
        ?int $rebarLayers = null,
        ?float $rebarReservePercent = null,
        ?float $formworkHeightM = null,
        ?float $formworkReservePercent = null,
        ?float $totalLengthM = null,
        ?float $widthM = null,
        ?float $heightM = null,
        ?float $houseLengthM = null,
        ?float $houseWidthM = null,
        ?array $segments = null,
        ?int $longitudinalBarsCount = null,
        ?float $longitudinalDiameterMm = null,
        ?float $longitudinalReservePercent = null,
        ?float $transverseDiameterMm = null,
        ?float $transverseStepMm = null,
        ?float $transverseReservePercent = null,
        ?string $pileType = null,
        ?bool $includePiles = null,
        ?int $pilesCount = null,
        ?float $pileShaftDiameterM = null,
        ?float $pileShaftHeightM = null,
        ?bool $includePileBase = null,
        ?float $pileBaseDiameterM = null,
        ?float $pileBaseHeightM = null,
        ?bool $includeGrillage = null,
        ?bool $includePileReinforcement = null,
        ?int $pileReinforcementBarsCount = null,
        ?float $pileReinforcementDiameterMm = null,
        ?float $pileReinforcementReservePercent = null,
        ?array $mixture = null,
        ?bool $useUnifiedConcreteMixtureSettings = null,
        ?array $pileMixture = null,
        ?array $grillageMixture = null,
        ?string $brickFormat = null,
        ?float $brickLengthMm = null,
        ?float $brickWidthMm = null,
        ?float $brickHeightMm = null,
        ?float $jointThicknessMm = null,
        ?string $wallThicknessType = null,
        ?float $wallLengthM = null,
        ?float $wallHeightM = null,
        ?float $reservePercent = null,
        ?bool $includeOpenings = null,
        ?array $windows = null,
        ?array $doors = null,
        ?bool $includeGables = null,
        ?array $gables = null,
        ?bool $includeMasonryMesh = null,
        ?int $masonryMeshFrequencyRows = null,
        ?bool $useCustomMortarProportions = null,
        ?float $cementShare = null,
        ?float $sandShare = null,
        ?string $cementPurchaseUnit = null,
        ?float $cementUnitWeightKg = null,
        ?float $cementUnitPrice = null,
        ?string $sandPurchaseUnit = null,
        ?float $sandUnitWeightKg = null,
        ?float $sandUnitPrice = null,
        ?float $cementBagWeightKg = null,
        ?float $brickWeightKg = null,
        ?float $brickPricePerUnit = null,
        ?float $cementBagPrice = null,
        ?float $sandPricePerTonne = null,
        ?string $tileTarget = null,
        ?float $tileLengthMm = null,
        ?float $tileWidthMm = null,
        ?float $tileThicknessMm = null,
        ?float $tileJointMm = null,
        ?string $tileLayingPattern = null,
        ?float $tileOffsetPercent = null,
        ?bool $tileIncludeOpenings = null,
        ?array $tileOpenings = null,
        ?bool $tileIncludeCutouts = null,
        ?array $tileCutouts = null,
        ?bool $tileIncludeAdhesive = null,
        ?float $tileAdhesiveConsumptionKgPerM2 = null,
        ?float $tileAdhesiveLayerMm = null,
        ?float $tileAdhesiveBagWeightKg = null,
        ?float $tileAdhesiveBagPrice = null,
        ?bool $tileIncludeGrout = null,
        ?float $tileGroutDensityKgPerM3 = null,
        ?float $tileGroutPackWeightKg = null,
        ?float $tileGroutPackPrice = null,
        ?float $tilePricePerM2 = null,
        ?string $drywallTarget = null,
        ?float $drywallSheetLengthMm = null,
        ?float $drywallSheetWidthMm = null,
        ?float $drywallSheetThicknessMm = null,
        ?int $drywallLayers = null,
        ?float $drywallFrameStepMm = null,
        ?float $drywallProfileWidthMm = null,
        ?float $drywallFastenerReservePercent = null,
        ?bool $drywallIncludeEndCladding = null,
        ?bool $drywallIncludeFinishing = null,
        ?bool $drywallIncludeCosts = null,
        ?float $drywallSheetPrice = null,
        ?float $drywallProfilePricePerLm = null,
        ?float $drywallFastenerPricePer100 = null,
        ?float $drywallPrimerPricePerKg = null,
        ?float $drywallJointPuttyPricePerKg = null,
        ?float $drywallFinishPuttyPricePerKg = null,
        ?float $drywallTapePricePerLm = null
    ): EstimateResult
    {
        if (!in_array($calculator, self::ALLOWED_CALCULATORS, true)) {
            throw new InvalidArgumentException('Field "calculator" must be one of: brick, screed, drywall, tile, slab_foundation, strip_foundation, pile_foundation.');
        }

        $input = new EstimateInput(
            mode: $mode,
            area: $area,
            thickness: $thickness,
            subType: $subType,
            tileLengthCm: $tileLengthCm,
            tileWidthCm: $tileWidthCm,
            length: $length,
            width: $width,
            height: $height,
            includeReinforcement: $includeReinforcement,
            includeFormwork: $includeFormwork,
            rebarDiameterMm: $rebarDiameterMm,
            rebarStepMm: $rebarStepMm,
            rebarLayers: $rebarLayers,
            rebarReservePercent: $rebarReservePercent,
            formworkHeightM: $formworkHeightM,
            formworkReservePercent: $formworkReservePercent,
            totalLengthM: $totalLengthM,
            widthM: $widthM,
            heightM: $heightM,
            houseLengthM: $houseLengthM,
            houseWidthM: $houseWidthM,
            segments: $segments,
            longitudinalBarsCount: $longitudinalBarsCount,
            longitudinalDiameterMm: $longitudinalDiameterMm,
            longitudinalReservePercent: $longitudinalReservePercent,
            transverseDiameterMm: $transverseDiameterMm,
            transverseStepMm: $transverseStepMm,
            transverseReservePercent: $transverseReservePercent,
            pileType: $pileType,
            includePiles: $includePiles,
            pilesCount: $pilesCount,
            pileShaftDiameterM: $pileShaftDiameterM,
            pileShaftHeightM: $pileShaftHeightM,
            includePileBase: $includePileBase,
            pileBaseDiameterM: $pileBaseDiameterM,
            pileBaseHeightM: $pileBaseHeightM,
            includeGrillage: $includeGrillage,
            includePileReinforcement: $includePileReinforcement,
            pileReinforcementBarsCount: $pileReinforcementBarsCount,
            pileReinforcementDiameterMm: $pileReinforcementDiameterMm,
            pileReinforcementReservePercent: $pileReinforcementReservePercent,
            mixture: $mixture,
            useUnifiedConcreteMixtureSettings: $useUnifiedConcreteMixtureSettings,
            pileMixture: $pileMixture,
            grillageMixture: $grillageMixture,
            brickFormat: $brickFormat,
            brickLengthMm: $brickLengthMm,
            brickWidthMm: $brickWidthMm,
            brickHeightMm: $brickHeightMm,
            jointThicknessMm: $jointThicknessMm,
            wallThicknessType: $wallThicknessType,
            wallLengthM: $wallLengthM,
            wallHeightM: $wallHeightM,
            reservePercent: $reservePercent,
            includeOpenings: $includeOpenings,
            windows: $windows,
            doors: $doors,
            includeGables: $includeGables,
            gables: $gables,
            includeMasonryMesh: $includeMasonryMesh,
            masonryMeshFrequencyRows: $masonryMeshFrequencyRows,
            useCustomMortarProportions: $useCustomMortarProportions,
            cementShare: $cementShare,
            sandShare: $sandShare,
            cementPurchaseUnit: $cementPurchaseUnit,
            cementUnitWeightKg: $cementUnitWeightKg,
            cementUnitPrice: $cementUnitPrice,
            sandPurchaseUnit: $sandPurchaseUnit,
            sandUnitWeightKg: $sandUnitWeightKg,
            sandUnitPrice: $sandUnitPrice,
            cementBagWeightKg: $cementBagWeightKg,
            brickWeightKg: $brickWeightKg,
            brickPricePerUnit: $brickPricePerUnit,
            cementBagPrice: $cementBagPrice,
            sandPricePerTonne: $sandPricePerTonne,
            tileTarget: $tileTarget,
            tileLengthMm: $tileLengthMm,
            tileWidthMm: $tileWidthMm,
            tileThicknessMm: $tileThicknessMm,
            tileJointMm: $tileJointMm,
            tileLayingPattern: $tileLayingPattern,
            tileOffsetPercent: $tileOffsetPercent,
            tileIncludeOpenings: $tileIncludeOpenings,
            tileOpenings: $tileOpenings,
            tileIncludeCutouts: $tileIncludeCutouts,
            tileCutouts: $tileCutouts,
            tileIncludeAdhesive: $tileIncludeAdhesive,
            tileAdhesiveConsumptionKgPerM2: $tileAdhesiveConsumptionKgPerM2,
            tileAdhesiveLayerMm: $tileAdhesiveLayerMm,
            tileAdhesiveBagWeightKg: $tileAdhesiveBagWeightKg,
            tileAdhesiveBagPrice: $tileAdhesiveBagPrice,
            tileIncludeGrout: $tileIncludeGrout,
            tileGroutDensityKgPerM3: $tileGroutDensityKgPerM3,
            tileGroutPackWeightKg: $tileGroutPackWeightKg,
            tileGroutPackPrice: $tileGroutPackPrice,
            tilePricePerM2: $tilePricePerM2,
            drywallTarget: $drywallTarget,
            drywallSheetLengthMm: $drywallSheetLengthMm,
            drywallSheetWidthMm: $drywallSheetWidthMm,
            drywallSheetThicknessMm: $drywallSheetThicknessMm,
            drywallLayers: $drywallLayers,
            drywallFrameStepMm: $drywallFrameStepMm,
            drywallProfileWidthMm: $drywallProfileWidthMm,
            drywallFastenerReservePercent: $drywallFastenerReservePercent,
            drywallIncludeEndCladding: $drywallIncludeEndCladding,
            drywallIncludeFinishing: $drywallIncludeFinishing,
            drywallIncludeCosts: $drywallIncludeCosts,
            drywallSheetPrice: $drywallSheetPrice,
            drywallProfilePricePerLm: $drywallProfilePricePerLm,
            drywallFastenerPricePer100: $drywallFastenerPricePer100,
            drywallPrimerPricePerKg: $drywallPrimerPricePerKg,
            drywallJointPuttyPricePerKg: $drywallJointPuttyPricePerKg,
            drywallFinishPuttyPricePerKg: $drywallFinishPuttyPricePerKg,
            drywallTapePricePerLm: $drywallTapePricePerLm
        );

        $calculatorService = $this->calculatorRegistry->resolve($calculator, $mode);

        return $calculatorService->calculate($input);
    }
}
